services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET_ARCH: amd64
        NDK_VERSION: 23
    volumes:
      - ./rootfs/data:/app/rootfs/data
    ports:
      - "127.0.0.1:10020:10020"
      - "127.0.0.1:20020:20020"
      - "127.0.0.1:30020:30020"
    stdin_open: true
    tty: true
    environment:
      USERNAME: ${USERNAME:-}
